import * as file from "N/file";

export namespace FILETYPES {
    export const NON_BIN = [
        file.Type.CSV,
        file.Type.HTMLDOC,
        file.Type.JAVASCRIPT,
        file.Type.MESSAGERFC,
        file.Type.PLAINTEXT,
        file.Type.POSTSCRIPT,
        file.Type.RTF,
        file.Type.SMS,
        file.Type.STYLESHEET,
        file.Type.XMLDOC,
    ];
    export const EXT = {
        dwg: file.Type.AUTOCAD,
        bmp: file.Type.BMPIMAGE,
        csv: file.Type.CSV,
        xls: file.Type.EXCEL,
        swf: file.Type.FLASH,
        gif: file.Type.GIFIMAGE,
        gz: file.Type.GZIP,
        htm: file.Type.HTMLDOC,
        html: file.Type.HTMLDOC,
        ico: file.Type.ICON,
        js: file.Type.JAVASCRIPT,
        jpg: file.Type.JPGIMAGE,
        eml: file.Type.MESSAGERFC,
        mp3: file.Type.MP3,
        mpg: file.Type.MPEGMOVIE,
        mpp: file.Type.MSPROJECT,
        pdf: file.Type.PDF,
        pjpeg: file.Type.PJPGIMAGE,
        txt: file.Type.PLAINTEXT,
        png: file.Type.PNGIMAGE,
        ps: file.Type.POSTSCRIPT,
        ppt: file.Type.POWERPOINT,
        mov: file.Type.QUICKTIME,
        rtf: file.Type.RTF,
        sms: file.Type.SMS,
        css: file.Type.STYLESHEET,
        tiff: file.Type.TIFFIMAGE,
        vsd: file.Type.VISIO,
        doc: file.Type.WORD,
        xml: file.Type.XMLDOC,
        zip: file.Type.ZIP,
    };
}
